### PR TITLE
Turn off comma-dangle rule

### PR DESCRIPTION
**Pull request by tiagoamaro**
It seems this rule isn't very popular, so I'm proposing turning it off.

### CODE REVIEW

**Comment by tiagoamaro** [comment]
[Ignore comma dangle on tc-eslint-config](https://trello.com/c/i42OyOHv/10631-ignore-comma-dangle-on-tc-eslint-config)

**Comment by tiagoamaro** [comment]
IMO, disabling the `comma-dangle` is a matter of making it a personal choice on when to use it, instead of requiring arrays, objects and functions to have it.

Example: personally, I would never dangling commas on imports, exports or function endings, as a more strict `comma-dangle` rule suggests: `import {a,} from "foo";`, `export {a,};` and `() => (a,);`.

**Comment by nickbrowne** [comment]
For me the main benefit of this rule is cleaning up diffs in commits, so that doing things like adding to arrays or objects doesn't show changes in lines that haven't changed meaning. 

Is there a way we can just reduce the strictness of this rule if some find it overbearing? I quite like it myself!

**Comment by tiagoamaro** [comment]
Sure thing @nickbrowne, I think my objections against this rule is forcing functions, imports and exports, but everything else is comprehensible. What do you think on enabling like this?

```
{
    "comma-dangle": ["error", {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "never",
        "exports": "never",
        "functions": "ignore"
    }]
}
```

In this case, "functions" is setup to "ignore" to match the default ESlint value, according to the docs:

> `functions` is set to "ignore" by default for consistency with the string option.
> - https://eslint.org/docs/rules/comma-dangle

This rule set would accept the following syntaxes (examples from the eslint doc page):

```js
// Multi-line array and objects need to have a dangling comma: "always-multiline".
const a = [
  1,
];
const b = {
  a: 1,
  b: 1,
}; 

// Array literals and array patterns of destructuring won't need commas, unless they're multiline 
const [a] = [1];
const [b, a] = [
  1,
  2,
];

// Same for objects
const { a } = { a: 1 };

// Never use dangling commas for imports, exports
import { a } from "foo";
export { a };

// Use dangling commas on functions at will.
const b = ary.filter(element =>
  console.log(element)
);

const b = ary.filter(element =>
  console.log(element),
);
```

(inviting @nullobject to discuss this as well)

**Comment by nickbrowne** [comment]
Yep, I think your proposed changes make sense :+1:

**Comment by markcipolla** [comment]
LGTM 👍

**Comment by nickbrowne** [comment]
I'll make the actual proposed changes in another PR.

**Comment by benmacleod** [comment]
OK, good, @nickbrowne, I was confused for a sec.

**Pull request merged**
